import registerIllusRight from "@/static/register-illus-right.svg";
import {userInfoKeyState} from "@/state";
import {useSetAtom} from "jotai";
import {useMemo,useState} from "react";
import toast from "react-hot-toast";
import {loginMember,registerMember} from "@/services/member.service";
export default function Register(){
 const refresh=useSetAtom(userInfoKeyState);const [mode,setMode]=useState<"choice"|"register"|"login">("choice");const [saving,setSaving]=useState(false);
 const [name,setName]=useState(""),[phone,setPhone]=useState(""),[email,setEmail]=useState(""),[address,setAddress]=useState(""),[password,setPassword]=useState("");
 const p=useMemo(()=>phone.replace(/\s+/g,"").trim(),[phone]);
 async function submit(){if(!p){toast.error("Vui lòng nhập số điện thoại.");return;}if(password.length<6){toast.error("Mật khẩu phải có ít nhất 6 ký tự.");return;}if(mode==="register"&&!name.trim()){toast.error("Vui lòng nhập họ và tên.");return;}try{setSaving(true);if(mode==="register")await registerMember({name:name.trim(),phone:p,email:email.trim(),address:address.trim(),password});else await loginMember(p,password);refresh(k=>k+1);toast.success(mode==="register"?"Đăng ký thành viên thành công.":"Đăng nhập thành công.");}catch(e){toast.error(e instanceof Error?e.message:"Không thể thực hiện.");}finally{setSaving(false);}}
 if(mode==="choice")return <div className="space-y-2"><button type="button" className="w-full rounded-lg bg-primary p-4 text-left text-white bg-cover" style={{backgroundImage:`url(${registerIllusRight})`,backgroundRepeat:"no-repeat",backgroundPosition:"bottom right"}} onClick={()=>setMode("register")}><div className="text-lg">Đăng ký thành viên</div><div className="text-2xs">Đăng ký để tích điểm và nhận ưu đãi</div></button><button type="button" className="w-full rounded-lg border border-primary bg-white p-3 font-medium text-primary" onClick={()=>setMode("login")}>Đăng nhập thành viên</button></div>;
 return <div className="rounded-lg border border-black/10 bg-white p-4 space-y-3"><div className="text-lg font-semibold">{mode==="register"?"Đăng ký thành viên":"Đăng nhập thành viên"}</div>{mode==="register"&&<input className="w-full rounded-lg border px-3 py-3" value={name} onChange={e=>setName(e.target.value)} placeholder="Họ và tên *"/>}<input className="w-full rounded-lg border px-3 py-3" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Số điện thoại *"/><input className="w-full rounded-lg border px-3 py-3" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Mật khẩu (ít nhất 6 ký tự) *"/>{mode==="register"&&<><input className="w-full rounded-lg border px-3 py-3" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><textarea className="w-full rounded-lg border px-3 py-3" value={address} onChange={e=>setAddress(e.target.value)} placeholder="Địa chỉ" rows={3}/></>}<div className="flex gap-2"><button className="flex-1 rounded-lg border px-4 py-3" onClick={()=>setMode("choice")}>Quay lại</button><button disabled={saving} className="flex-1 rounded-lg bg-primary px-4 py-3 text-white" onClick={submit}>{saving?"Đang xử lý...":mode==="register"?"Đăng ký":"Đăng nhập"}</button></div></div>;
}
